name: Cloud Run Jobs CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'cloud_run_job/**'
  push:
    branches: [ main ]
    paths:
      - 'cloud_run_job/**'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - cloud_run_job/hello-world

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_google_credentials: ${{ secrets.GCP_SA_KEY }}
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_project_id: "trading-prod-468212"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ matrix.directory }}

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ matrix.directory }}

      - name: Terraform Format (Auto-fix on failure)
        if: failure()
        run: |
          echo "Auto-formatting Terraform files..."
          terraform fmt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Auto-format Terraform files"
        working-directory: ${{ matrix.directory }}
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.directory }}

      # Cloud Run関連の既存リソースをstateにインポート（エラーが出ても継続）
      - name: Import Existing Cloud Run Resources (if any)
        run: |
          echo "Attempting to import existing Cloud Run job and scheduler..."
          # Cloud Run Jobのインポートを試行
          terraform import google_cloud_run_v2_job.hello_world_job "projects/$TF_VAR_project_id/locations/asia-northeast1/jobs/hello-world-daily-job" || echo "Cloud Run job import failed or doesn't exist - continuing..."
          
          # Cloud Schedulerのインポートを試行
          terraform import google_cloud_scheduler_job.hello_world_scheduler "projects/$TF_VAR_project_id/locations/asia-northeast1/jobs/hello-world-daily-scheduler" || echo "Scheduler job import failed or doesn't exist - continuing..."
        working-directory: ${{ matrix.directory }}
        continue-on-error: true

      # PR時は plan だけ出す
      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        run: |
          # 通常のplanを実行
          terraform plan -no-color -out=tfplan
          
          echo "=== Terraform Plan Output ==="
          terraform show -no-color tfplan
        working-directory: ${{ matrix.directory }}

      # main へ push（=マージ後）は apply
      - name: Terraform Plan (main)
        if: github.event_name == 'push'
        run: |
          # 通常のplanを実行
          terraform plan -no-color -out=tfplan
          
          echo "=== Terraform Plan Output ==="
          terraform show -no-color tfplan
        working-directory: ${{ matrix.directory }}

      - name: Terraform Apply (main)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ matrix.directory }}

      # Apply後のリソース確認
      - name: Verify Cloud Run Job Deployment
        if: github.event_name == 'push'
        run: |
          echo "Verifying Cloud Run job deployment..."
          
          # Cloud Run jobの状態確認
          if command -v gcloud &> /dev/null; then
            gcloud run jobs describe hello-world-daily-job --region=asia-northeast1 --project=$TF_VAR_project_id || echo "Could not describe job - may not exist yet"
            gcloud scheduler jobs describe hello-world-daily-scheduler --location=asia-northeast1 --project=$TF_VAR_project_id || echo "Could not describe scheduler - may not exist yet"
          else
            echo "gcloud CLI not available - skipping verification"
          fi
        continue-on-error: true
