name: Terraform CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - external_tables/asset_name_master
          - external_tables/asset_status_history

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_google_credentials: ${{ secrets.GCP_SA_KEY }}
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_project_id: "trading-prod-468212"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ matrix.directory }}

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ matrix.directory }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.directory }}

      # 既存リソースをstateにインポート（エラーが出ても継続）
      - name: Import Existing Resources (if any)
        run: |
          # テーブル名を動的に設定
          if [[ "${{ matrix.directory }}" == "external_tables/asset_name_master" ]]; then
            TABLE_ID="raw_asset_name_master"
          elif [[ "${{ matrix.directory }}" == "external_tables/asset_status_history" ]]; then
            TABLE_ID="raw_asset_status_history"
          fi
          
          # 既存のBigQueryテーブルをインポートを試行（失敗しても継続）
          echo "Attempting to import existing table: $TABLE_ID"
          terraform import google_bigquery_table.external_sheet "$TF_VAR_project_id:TEMP:$TABLE_ID" || echo "Import failed or resource doesn't exist - continuing..."
        working-directory: ${{ matrix.directory }}
        continue-on-error: true

      # PR時は plan だけ出す
      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        run: |
          # 通常のplanを実行
          terraform plan -no-color -out=tfplan
          
          # planに変更がある場合の詳細確認
          if terraform show -no-color tfplan | grep -E "(will be created|will be updated|will be destroyed)" > /dev/null; then
            echo "Changes detected in plan"
            # 既存テーブルとの競合を避けるため、replaceオプションでplanを再作成
            terraform plan -no-color -replace=google_bigquery_table.external_sheet -out=tfplan
          else
            echo "No changes detected"
          fi
        working-directory: ${{ matrix.directory }}

      # main へ push（=マージ後）は apply
      - name: Terraform Plan (main)
        if: github.event_name == 'push'
        run: |
          # 通常のplanを実行
          terraform plan -no-color -out=tfplan
          
          # planに変更がある場合の詳細確認
          if terraform show -no-color tfplan | grep -E "(will be created|will be updated|will be destroyed)" > /dev/null; then
            echo "Changes detected in plan"
            # 既存テーブルとの競合を避けるため、replaceオプションでplanを再作成
            terraform plan -no-color -replace=google_bigquery_table.external_sheet -out=tfplan
          else
            echo "No changes detected"
          fi
        working-directory: ${{ matrix.directory }}

      - name: Terraform Apply (main)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ matrix.directory }}
